<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-01T09:00:43 ICT" name="N11 Test Suite" finished-at="2022-08-01T09:00:56 ICT" duration-ms="12751">
    <groups>
    </groups>
    <test started-at="2022-08-01T09:00:43 ICT" name="LoginTest" finished-at="2022-08-01T09:00:56 ICT" duration-ms="12751">
      <class name="tests.LoginTests">
        <test-method is-config="true" signature="classLevelSetup()[pri:0, instance:tests.LoginTests@78525ef9]" started-at="2022-08-01T09:00:44 ICT" name="classLevelSetup" finished-at="2022-08-01T09:00:46 ICT" duration-ms="2018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classLevelSetup -->
        <test-method is-config="true" signature="methodLevelSetup()[pri:0, instance:tests.LoginTests@78525ef9]" started-at="2022-08-01T09:00:46 ICT" name="methodLevelSetup" finished-at="2022-08-01T09:00:46 ICT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method signature="EmptyUserEmptyPassword(java.lang.reflect.Method)[pri:1, instance:tests.LoginTests@78525ef9]" started-at="2022-08-01T09:00:46 ICT" name="EmptyUserEmptyPassword" description="Invalid Login Scenario with empty username and password." finished-at="2022-08-01T09:00:51 ICT" duration-ms="5516" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTests.EmptyUserEmptyPassword(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nopCommerce demo store12345] but found [nopCommerce demo store. Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store12345] but found [nopCommerce demo store. Login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.LoginTests.EmptyUserEmptyPassword(LoginTests.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EmptyUserEmptyPassword -->
        <test-method is-config="true" signature="methodLevelSetup()[pri:0, instance:tests.LoginTests@78525ef9]" started-at="2022-08-01T09:00:52 ICT" name="methodLevelSetup" finished-at="2022-08-01T09:00:52 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodLevelSetup -->
        <test-method signature="InvalidUserNameInvalidPassword(java.lang.reflect.Method)[pri:0, instance:tests.LoginTests@78525ef9]" started-at="2022-08-01T09:00:52 ICT" name="InvalidUserNameInvalidPassword" description="Invalid Login Scenario with wrong username and password." finished-at="2022-08-01T09:00:56 ICT" duration-ms="4255" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.LoginTests.InvalidUserNameInvalidPassword(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidUserNameInvalidPassword -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.LoginTests@78525ef9]" started-at="2022-08-01T09:00:56 ICT" name="teardown" finished-at="2022-08-01T09:00:56 ICT" duration-ms="81" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.LoginTests -->
    </test> <!-- LoginTest -->
  </suite> <!-- N11 Test Suite -->
</testng-results>
